### ISSUE TITLE
Can't get nix-linter to work

### ISSUE THREAD

**Issue by t184256** [iamcco/coc-diagnostic#61] opened 2020-11-12 02:17 UTC
**Describe the bug**
Can't get nix-linter to work.

**To Reproduce**
1. Ensure `nix-linter somefile.nix` works and outputs human-readable warnings
2. Ensure `nix-linter --json somefile.nix` outputs the same in json
3. Enable coc-diagnostic as a neovim plugin
4. Override 
```
diagnostic-languageserver.filetypes.nix = "nix-linter";
diagnostic-languageserver.mergeConfig = true;
diagnostic-languageserver.linters.nix-linter.args = [ "--json" "%filepath"];
```
so that it at least outputs json we're expecting

5. Launch `nvim somefile.nix`
6. Observe no warnings
7. `:CocInfo`, see
```
## Output channel: diagnostic-languageserver
[Error  - 03.08.02] [nix] diagnostic handle fail: [nix-linter] (intermediate value)(intermediate value)(intermediate value).map is not a function
```

**Expected behavior**
I expect to see warnings from nix-linter and no errors in `:CocInfo`

**Desktop (please complete the following information):**
 - OS: NixOS 20.09
 - coc-diagnostic-0.13.0 (I used node2nix)
 - nix-linter-unstable-2020-09-25

Log:
```
2020-11-12T03:10:55.396 INFO (pid:28952) [services] - registered service "languageserver.bash"
2020-11-12T03:10:55.398 INFO (pid:28952) [services] - registered service "languageserver.ccls"
2020-11-12T03:10:55.398 INFO (pid:28952) [services] - registered service "languageserver.nix"
2020-11-12T03:10:55.403 INFO (pid:28952) [services] - nix state change: stopped => starting
2020-11-12T03:10:55.403 INFO (pid:28952) [services] - registered service "languageserver.python"
2020-11-12T03:10:55.469 INFO (pid:28952) [services] - registered service "highlight"
2020-11-12T03:10:55.498 INFO (pid:28952) [services] - registered service "diagnostic-languageserver"
2020-11-12T03:10:55.498 INFO (pid:28952) [services] - diagnostic language service state change: stopped => starting
2020-11-12T03:10:55.500 INFO (pid:28952) [plugin] - coc.nvim 0.0.78-9f9d8a32c4 initialized with node: v12.18.4 after 197ms
2020-11-12T03:10:55.506 INFO (pid:28952) [language-client-index] - Language server "languageserver.nix" started with 28971
2020-11-12T03:10:55.519 INFO (pid:28952) [language-client-index] - highlight started with 28974
2020-11-12T03:10:55.526 INFO (pid:28952) [language-client-index] - diagnostic-languageserver started with 28980
2020-11-12T03:10:55.542 INFO (pid:28952) [services] - nix state change: starting => running
2020-11-12T03:10:55.549 INFO (pid:28952) [services] - service languageserver.nix started
2020-11-12T03:10:55.677 INFO (pid:28952) [services] - diagnostic language service state change: starting => running
2020-11-12T03:10:55.678 INFO (pid:28952) [services] - service diagnostic-languageserver started
```

Other linters work fine.

@expipiplus1

**Comment by expipiplus1** [comment] 2020-11-12 02:28
Hmm, perhaps there was some issue when I transcribed my settings into config.js here.

These are my settings for nix-linter: https://github.com/expipiplus1/dotfiles/blob/ad1307722562678f1194cc20fc8e2551f33d386e/config/nixpkgs/home/coc-nvim.nix#L172-L187

**Comment by expipiplus1** [comment] 2020-11-12 02:29
oh yeah, how did I miss this... the output of nix-linter needs to be wrapped in "[" "]"

**Comment by expipiplus1** [comment] 2020-11-12 02:33
It is due to this bug in nix-linter: https://github.com/Synthetica9/nix-linter/issues/44

Either
- That bug needs to be fixed in nix-linter (and config.ts changed to pass --json instead of --json-stream)
- You need to wrap nix-linter in a script which makes lines into a json list like this: https://github.com/expipiplus1/dotfiles/blob/ad1307722562678f1194cc20fc8e2551f33d386e/config/nixpkgs/home/coc-nvim.nix#L173-L177

I think I must have been using that wrapper by mistake when I tested this.

**Comment by t184256** [comment] 2020-11-12 10:53
@expipiplus1, thanks for investigating, good to know it's not me going crazy =)

I guess, I should use your workaround for now, and the general way forward would be to change coc-diagnostic to invoke nix-linter with `--json` and wait for Synthetica9/nix-linter#44 to be resolved.

**Comment by expipiplus1** [comment] 2020-11-12 10:55
The problem is that coc-diagnostic doesn't understand the output with `--json`, it needs to be surrounded with `[` and `]` and have commas between the elements.

**Comment by t184256** [comment] 2020-11-12 11:01
Yes, I understood that, but that's only needed until `--json` starts, well, outputting JSON. And I'd say it's a reasonable expectation.

**Comment by expipiplus1** [comment] 2020-11-12 11:02
Ah sorry, I didn't parse your comment correctly :D

**Comment by iamcco** [comment] 2020-11-13 03:37
To support this format output seems need to wrapper in `[]` and separate by `,`, right ? So we need an option to format the output before handle.

**Comment by expipiplus1** [comment] 2020-11-13 04:22
An alternative would be to load lines, each of which is valid json. This is what's output by the `--json-stream` option of nix-linter

**Comment by Freed-Wu** [comment] 2023-08-31 14:52
nix-linter has been marked broken on NixOS. <https://github.com/NixOS/nixpkgs/blob/nixos-23.05/pkgs/development/tools/analysis/nix-linter/default.nix#L46>

I advice to change other specific nix language server, such as nixd, rnix-lsp, nil.

**Closed by Freed-Wu** 2023-08-31 14:52 UTC
